### ISSUE TITLE
Add .id to ActionEvents

### ISSUE THREAD

**Issue by tonyandrewmeyer** [canonical/ops-scenario#101]
As of ops 2.11, [ActionEvent objects will have an `.id` attribute](https://github.com/canonical/operator/pull/1124) based on the `JUJU_ACTION_UUID` envvar. For now, there's a `None` default if the `ActionEvent` is created without providing the ID, to provide backwards compatibility (e.g. for Scenario).

Scenario should pass an ID / set JUJU_ACTION_UUID appropriately, so that when charms start making use of the `.id` attribute Scenario tests will work as expected.

**Comment by tonyandrewmeyer** [comment]
@PietroPasotti I'm happy to open a PR for this if you'd like - do you think that you'd want this to be provided in the `run_action` method, or to just have some sort of automatic ID, like Harness does? I'd personally go with the latter, since it's Juju that picks an ID rather than the user, but I'm not sure if that will impact things like creating states automatically?

**Comment by PietroPasotti** [comment]
Sure @tonyandrewmeyer, go ahead!
I think we should add it to the `Action` data structure using the same pattern as I used for the relation ID: a default auto-incrementing counter.

Off the top of my head, when you implement this, you'll have to:
- add the field to `state.Action` (see `state.RelationBase.relation_id`)
- use the value of the field in `runtime.Runtime._get_event_env` to populate the envvar the framework expects
- add a couple of tests
- I don't think this has consistency checker-related concerns
