### ISSUE TITLE
Containers should fail when can_connect is false

### ISSUE THREAD

**Issue by tonyandrewmeyer** [canonical/ops-scenario#102]
This currently passes:

```python
import ops

import scenario

class MyCharm(ops.CharmBase):
    def __init__(self, framework):
        super().__init__(framework)
        framework.observe(self.on.config_changed, self._on_config_changed)

    def _on_config_changed(self, event):
        self.unit.get_container("example").replan()

ctx = scenario.Context(
    MyCharm,
    meta={"name": "my-charm", "containers": {"example": {"resource": "ubuntu-22.04"}}},
)
container = scenario.Container("example", can_connect=False)
state = scenario.State(containers=[container])
out = ctx.run("config-changed", state=state)
```

However, if the container can't be connected to (`can_connect=False`), then the `replan()` should really fail, because that's what would really happen.

The current system works if you have code like:

```python
def _handle(self, event):
    if not self.container.can_connect():
        event.defer()
    try:
        self.container.replan()
    except ops.pebble.ConnectionError:
        event.defer()
```

But it does not if you adjust that to be like this, avoiding the pointless `can_connect` call:

```python
def _handle(self, event):
    try:
        self.container.replan()
    except ops.pebble.ConnectionError:
        event.defer()
```

If you're only testing the positive case, then it doesn't matter, but to test the negative case, you'd currently have to mock the `replan()` call.

It seems to me that the `scenario.Container` attributes/methods should fail when `can_connect` is false, if they would also fail if Pebble was not working in a deployment. Not sure if you agree @PietroPasotti?

**Comment by PietroPasotti** [comment]
I definitely agree and I cannot reproduce that locally. What scenario version are you running?

This test passes on main:

```python
def test_pebble_operations_fail_if_container_cannot_connect():
    ctx = Context(
        CharmBase,
        meta={
            "name": "my-charm",
            "containers": {"example": {"resource": "ubuntu-22.04"}},
        },
    )
    container = Container("example", can_connect=False)
    with ctx.manager("update-status", State(containers=[container])) as mgr:
        container = mgr.charm.unit.get_container("example")
        assert not container.can_connect()

        for call, args in (
            ("start", ("foo",)),
            ("restart", ("foo",)),
            ("stop", ("foo")),
            ("autostart", ()),
            ("replan", ()),
        ):
            with pytest.raises(pebble.ConnectionError):
                getattr(container, call)(*args)
```

**Comment by tonyandrewmeyer** [comment]
Sorry, my bad :disappointed:. I only did a very quick check (while working on docs that discourage always guarding with `can_connect()` and missed that Scenario absorbs exceptions silently.

ie. in Harness I can do this:

```python
h = ops.testing.Harness(MyCharm, meta="""
name: my-charm
containers:
  example:
    resource: ubuntu-22.04
""")
h.begin()
try:
    h.charm.on.config_changed.emit()
finally:
    h.cleanup()
```

And run it directly and it'll output a traceback to stderr and exit non-zero. With Scenario, there's no output (although the exit code is non-zero - I missed that).

Lesson learned: I will properly do pytests even when quickly checking something in the future :smile:.

**Comment by PietroPasotti** [comment]
Well maybe that's one thing to fix then, should we add some error logging?

**Comment by tonyandrewmeyer** [comment]
> Well maybe that's one thing to fix then, should we add some error logging?

Yeah, maybe. What's happening is that `ops.log.setup_root_logging()` sets up an except hook to redirect any unhandled exceptions to Juju's log, and Scenario captures everything that should go to the Juju log.

**Comment by tonyandrewmeyer** [comment]
> Well maybe that's one thing to fix then, should we add some error logging?

Yeah, maybe. What's happening is that `ops.log.setup_root_logging()` sets up an except hook to redirect any unhandled exceptions to Juju's log, and Scenario captures everything that should go to the Juju log.

I'm not sure that's really desired behaviour? You don't get to inspect the output state `.logs` because the process has crashed. When doing things the proper way and running under pytest, pytest catches the error and handles it appropriately.

Maybe after Scenario calls `setup_root_logging` it could do a `sys.excepthook = sys.__excepthook__`?

**Comment by PietroPasotti** [comment]
mmm, I was hoping to keep scenario testing framework agnostic

**Comment by tonyandrewmeyer** [comment]
> mmm, I was hoping to keep scenario testing framework agnostic

Resetting sys.excepthook would keep it agnostic. Or I think it might be ok to have `setup_root_logging` have an argument to avoid setting it - but I would need to convince the team of that (including completely convincing myself).
