### ISSUE TITLE
generate complete scenario test without a local charm repo

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/ops-scenario#13]
At the moment `scenario snapshot` is only able to guess the charm type name to use (`from charm import X`) to trigger the state execution if you execute it from the charm root (the charm repo). It searches for `./src/charm.py`.

This is because the most common use case is: you are developing/debugging a charm that you have locally cloned, and if you create a snapshot, you probably want to put it in `/charm-root/tests/scenario/snapshots/` and run them as part of your test suite.

This feature request is about a different user story: 
- you don't have access to the local charm root
- there's a charm running somewhere on some cloud that you want to debug/inspect locally without having to clone the source repo first

Suppose you don't have access to the charm root, and want to trigger a snapshotted state. That would mean snapshot would have to fetch not only the state, but also the charm sources, libs, venv, etc... Basically clone the unit's `/path-to/charm/` subtree in a local dir and prep it for use with the obtained state.

One would:
- `pip install ops-scenario[all]`

which installs
ops, black, pytest, other deps

- then run 
`/home/ubuntu/.local/bin/scenario snapshot demo-api-charm/0 --format=full-test  > my_excellent_test.py`

that will ssh into the charm container, extract charm folder, copy to local machine
then generate readable pytest file with extracted CharmClass name

- I would edit the test file to add an event name and probably some assertions

- and finally `pytest my_excellent_test.py`

and then I could adjust the charm source, iterate over the test code, etc...

**Comment by PietroPasotti** [comment]
@phvalguima is this a good use case in your opinion?

**Comment by PietroPasotti** [comment]
use case is foggy IMHO and we have no concrete requests for it. Closing for now.
