### ISSUE TITLE
strategies.py is an empty file

### ISSUE THREAD

**Issue by dimaqq** [canonical/ops-scenario#133]
the file was introduced in https://github.com/canonical/ops-scenario/commit/d72aac2034834698c9db8015b4ba61e89f1f501b

perhaps there was a plan for this file, that didn't materialise?

**Comment by PietroPasotti** [comment]
whoops, must have committed it by mistake when I was switching back and forth to [the hypothesis development branch](https://github.com/canonical/ops-scenario/tree/hypothesis-plugin) (I'm playing around with a hypothesis plugin to automatically generate variations of a State, pretty cool :)

**Comment by tonyandrewmeyer** [comment]
Both already removed in 7.0 :)

**Comment by dimaqq** [comment]
Happy to close in that case!
