### ISSUE TITLE
v6.0.4 requires ops >=2.12, but pyproject.toml only specifies >=2.10

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/ops-scenario#149]
using ops-scenario v6.0.4 with ops < 2.12 causes ` E   AttributeError: module 'ops' has no attribute 'CloudCredential'`

from https://github.com/canonical/ops-scenario/blob/da30b05f3cce60d33452abac184d8d1f0e66c7f2/scenario/state.py#L160

ops.CloudCredential only exists in ops 2.12+ (https://github.com/canonical/operator/commit/8097cca861eae31727636f92c932738d14d0ac81)

but pyproject.toml only requires >=2.10
https://github.com/canonical/ops-scenario/blob/77ce4477722d0ebd105130e42a54215d713a8dba/pyproject.toml#L21

**Comment by tonyandrewmeyer** [comment]
Fixed in #128, as an accidental drive-by.
