### ISSUE TITLE
Make mocked status_set raise an error for 'error' or 'unknown' statuses

### ISSUE THREAD

**Issue by benhoyt** [canonical/ops-scenario#202]
Harness's mocked status_set [raises an exception](https://github.com/canonical/operator/blob/98a4e4f44d37d3361a253bc1eff49eee2ca6d140/ops/_private/harness.py#L2494-L2498) if it's not one of the allowed statuses. We should do this in Scenario too. See [related thread](https://github.com/canonical/operator/pull/1386#issuecomment-2367411396).

**Comment by tonyandrewmeyer** [comment]
Opened a PR in operator.
