### ISSUE TITLE
add default relation keys in relation databags

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/ops-scenario#31]
At the moment, all databags are born empty.
They should have the default keys present and set to some sensible defaults.
e.g.:
```
egress-subnets   10.152.183.30/32              
ingress-address  10.152.183.30                 
private-address  10.152.183.30                 
```

**Comment by PietroPasotti** [comment]
@benhoyt @sed-i @Abuelodelanada I'm thinking of implementing it in an opt-in fashion:
- add a `scenario.STRICT_DATABAGS = os.getenv('STRICT_DATABAGS', False)` global
- add a warning that in 3.3 this will default to True and your tests may break
- if STRICT_DATABAGS: 
  - all 'null' databags created by e.g. `scenario.Relation(remote_unit_ids=[0,3,4])` will contain the default juju keys
  - add a post-init validation on scenario.RelationBase verifying that all databags contain the default juju keys.
  - add a `inject_juju_relation_data` helper to quickly add defaulted juju keys to a dict.
  
  
What do you think?

**Comment by tonyandrewmeyer** [comment]
@PietroPasotti did https://github.com/canonical/ops-scenario/commit/75a09fd2c80d046c9d6673743b8716cd10fec148 do what you intended here, or are you thinking that there'd be more on this?

**Comment by PietroPasotti** [comment]
no indeed, this issue is obsolete!
