### ISSUE TITLE
more pythonic api for [pre/post]-event

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/ops-scenario#53]
Right now if you want to run assertions on the charm instance or its children, you have to:

```python
def pre_event(charm):
    assert charm._private_attr is 'foo'

def post_event(charm):
    assert charm._private_attr is 'bar'

state_out = Context(CharmType).run(event, state_in, pre_event=pre_event, post_event=post_event) 

assert state_out.unit_status == ... 
```

because the charm instance only exists within the context of Context.run, and is discarded afterwards.

# alternative API to consider:

```python
with context.runs(state_in, event) as runner:
     assert runner.charm._private_attr is 'foo'
     state_out = runner.run()  # emit 'event', can only be called once
     assert runner.charm._private_attr is 'bar'
     
assert state_out.unit_status == ...  # business as usual
```

**Comment by PietroPasotti** [comment]
@simskij wdyt? @benhoyt

**Comment by simskij** [comment]
i personally prefer this style. it seems easier to follow to me.

**Comment by benhoyt** [comment]
Yeah, I also prefer that approach to the callbacks. Small suggestions:

1) What about calling it `context.runner()` so the name is not quite so close to the existing `context.run()` method name?
2) Is there a reason the order of the `state_in` and `event` params is opposite to `context.run()`? It would seem better to make them the same order for consistency.

In fact, is there a reason it needs to be a context manager? Could it just be this, or is there cleanup to do when the context manager exits?

```python
runner = context.runner(event, state_in)
assert runner.charm._private_attr is 'foo'
state_out = runner.run()  # emit 'event', can only be called once
assert runner.charm._private_attr is 'bar'

assert state_out.unit_status == ...  # business as usual
```

**Comment by PietroPasotti** [comment]
there needs to be cleanup, yeah. Context manager is the way

**Comment by PietroPasotti** [comment]
man aren't generators messy
