### ISSUE TITLE
how to assert status history

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/ops-scenario#6]
Sometimes it's handy not just to know the 'final' status of a charm after an event has fired, but also to know the intermediate statuses. E.g.:

`Unknown() --> Maintenance(installing) --> Waiting(for server to show up) --> Active()`

At the moment, short of checking the juju-log output, we can only assert that the final status is Active, but there's no way of verifying the intermediate ones. Should we add a `State.status_history`, where `State.status` returns `self.status_history[0]`, to facilitate this type of test?

**Comment by benhoyt** [comment]
I'm not sure we should be writing tests that test this level of detail. To me that seems like testing internal implementation details, like when you test with mocks and assert that some function was called exactly 3 times. Shouldn't tests only be concerned about the final (committed) state the the event code ends up in?

**Comment by benhoyt** [comment]
> statuses do get committed synchronously

Ah true, I'd forgotten about that. Makes sense in that case (though I think usage of this will/should be rare).
