### ISSUE TITLE
RuntimeError is raised instead of SecretNotFoundError

### ISSUE THREAD

**Issue by juditnovak** [canonical/ops-scenario#69]
Currently `RuntimeError` is raised when a Secret can not be retireved either by `id` or by `label` (https://github.com/canonical/ops-scenario/blob/main/scenario/mocking.py#L137-L142).

This is not in-line with the way the `ops` library works, throwing a `SecretNotFoundError` once a `get_secret()` operation couldn't succeed.

This issue is critial to our testsuite, as currently a `RuntiemeError` is raised blocking the workflow -- instead of executing our error handler for `SecretNotFoundError` -- carrying on with the subsequential part of the execution flow.

The fix is provided in this PR: https://github.com/canonical/ops-scenario/pull/68
Would you be so kind to consider it ASAP...?

Thank you very-very-very much in adavance.

**Comment by PietroPasotti** [comment]
Fixed by #68
